"""Change merchant to accept null values

Revision ID: 7666ffd34867
Revises: b9c8399d0880
Create Date: 2024-06-24 17:27:04.009842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7666ffd34867'
down_revision = 'b9c8399d0880'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('merchant',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('merchant',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###
